on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - run: npm install -g firebase-tools

      - run: |
          echo $FIREBASE_TOKEN | firebase login:ci --no-interactive

      - run: firebase deploy --only hosting

      - run: echo "Firebase deployment complete!"
